<nav>
	<a href="index.php" title="Home page" class="btn">HOME</a>
		<div class="dropdown">
			<a href="jobs.php" class="btn" title="Job descriptions">CAREER </a>
			 <div class="dropdown-content">
				<a href="jobs.php#cloud">Cloud Architect</a>
				 <a href="jobs.php#system">Mainframe Developer</a>
				 <a href="images/sad.jpg" target="_blank">Test Analyst</a>
			 </div>
		 </div>
		<a href="apply.php" class="btn" title="Apply jobs">APPLY</a>
		<a href="manage.php" class="btn" title="Manage jobs">MANAGE</a>
		<a href="about.php" class="btn" title="About author">ABOUT</a>
		<div class="dropdown">
			<p class="btn">ENHANCEMENTS</p>
			<div class="dropdown-content">
				<a href="enhancements.php" title="enhancements made to the code">CSS enhancements</a>
				<a href="enhancements2.php" title="enhancements made to the code">Javascript enhancements</a>
		</div>
	</div>
	<a href="mailto:102005528@student.swin.edu.au" class="btn" title="Contact details" >Contact Us</a>
</nav>